name: TagScanner
options:
  bundleIdPrefix: com.tagscanner
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    INFOPLIST_FILE: Sources/TagScanner/Info.plist

targets:
  TagScanner:
    type: application
    platform: iOS
    sources:
      - path: Sources/TagScanner
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tagscanner.app
        INFOPLIST_FILE: Sources/TagScanner/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    info:
      path: Sources/TagScanner/Info.plist
      properties:
        CFBundleDisplayName: Tag Scanner
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "Tag Scanner needs camera access to photograph clothing tags for analysis."
        NSPhotoLibraryUsageDescription: "Tag Scanner needs photo library access to select existing photos of clothing tags."
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - tagscanner
        CONVEX_URL: "https://qualified-sheep-863.convex.cloud"
        WORKOS_CLIENT_ID: "$(WORKOS_CLIENT_ID)"
        WORKOS_REDIRECT_URI: "tagscanner://callback"
    entitlements:
      path: Sources/TagScanner/TagScanner.entitlements

schemes:
  TagScanner:
    build:
      targets:
        TagScanner: all
    run:
      config: Debug
      environmentVariables:
        - variable: WORKOS_CLIENT_ID
          value: "$(WORKOS_CLIENT_ID)"
          isEnabled: true
        - variable: CONVEX_URL
          value: "https://qualified-sheep-863.convex.cloud"
          isEnabled: true
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

